name: .NET - coverlet test coverage

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Determine PR Mode
        id: pr-mode
        run: |
          if [[ "develop" == "develop" || "develop" == "main" ]]; then
            echo "pr_mode=false" >> $GITHUB_ENV
          else
            echo "pr_mode=true" >> $GITHUB_ENV
          fi
          
          # Load the updated environment variable
          source $GITHUB_ENV
          
          # Print the value of pr_mode
          echo "PR Mode is: $pr_mode"


    
